### ISSUE TITLE
times for electrofishing samples

### ISSUE THREAD

**Issue by matthewodonnell** [Conte-Ecology/westBrookData#50]
Currently detection time is not included for fish that are captured via electrofishing. To be able to use electrofishing data in conjunction with antenna or acoustic data, we need to add in start time for each capture to createCoreData

**Comment by evanchildress** [comment]
these are now contained in detection_date. Times aren't available for much of the data in the pre-2000 era, so those get 12:00:00, which shouldn't matter because antennas didn't exist. I do not know the EST vs EDT considerations that are needed here, but these are all presumably in current, local time, which is how they are currently treated. Time-change issues should matter more for antenna data.
